/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "on-tertiary-container": "#be8f61",
        "secondary-fixed": "#b1f0ce",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#623f18",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#2c1600",
        "on-primary-fixed": "#002114",
        "on-primary-fixed-variant": "#2c4d3d",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#7ca08c",
        "outline-variant": "#c1c8c2",
        "on-secondary-fixed": "#002114",
        "on-secondary-container": "#316e52",
        "surface-container-low": "#eff4ff",
        "inverse-on-surface": "#eaf1ff",
        "on-surface-variant": "#414844",
        "surface-container": "#e6eeff",
        "tertiary": "#2c1600",
        "primary-container": "#143627",
        "outline": "#727973",
        "surface-container-high": "#dee9fc",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#f0bd8b",
        "surface-bright": "#f8f9ff",
        "surface-variant": "#d9e3f6",
        "surface-dim": "#d0dbed",
        "surface-tint": "#436554",
        "on-surface": "#121c2a",
        "inverse-primary": "#aacfba",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#aacfba",
        "on-error": "#ffffff",
        "background": "#f8f9ff",
        "surface-container-highest": "#d9e3f6",
        "tertiary-fixed": "#ffdcbd",
        "tertiary-container": "#482904",
        "secondary-container": "#aeeecb",
        "primary": "#002013",
        "on-secondary-fixed-variant": "#0e5138",
        "on-background": "#121c2a",
        "primary-fixed": "#c5ebd5",
        "secondary": "#2c694e",
        "inverse-surface": "#27313f",
        "secondary-fixed-dim": "#95d4b3",
        "surface": "#f8f9ff"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "space-sm": "0.5rem",
        "gutter-mobile": "1rem",
        "space-lg": "1.5rem",
        "space-xs": "0.25rem",
        "space-xxl": "4rem",
        "space-xl": "2.5rem",
        gutter: "1.5rem",
        "space-md": "1rem",
        "margin-mobile": "1.25rem",
        margin: "3rem"
      },
      fontFamily: {
        "headline-lg": ["Playfair Display", "serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Playfair Display", "serif"],
        display: ["Playfair Display", "serif"],
        "display-mobile": ["Playfair Display", "serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "stat-display": ["Playfair Display", "serif"],
        "label-lg": ["Plus Jakarta Sans", "sans-serif"],
        "title-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "title-md": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "headline-md": ["26px", { lineHeight: "34px", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        display: ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-mobile": ["34px", { lineHeight: "42px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-lg": ["17px", { lineHeight: "28px", fontWeight: "400" }],
        "stat-display": ["40px", { lineHeight: "44px", fontWeight: "700" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "title-lg": ["18px", { lineHeight: "26px", fontWeight: "700" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "title-md": ["16px", { lineHeight: "24px", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
